CREATE DATABASE goblog;

USE goblog;

create table IF NOT EXISTS `user` (
    uid INT AUTO_INCREMENT PRIMARY KEY COMMENT '用户id',
    username VARCHAR(50) NOT NULL COMMENT '用户名',
    avatar VARCHAR(100) NOT NULL COMMENT '头像',
    passwd VARCHAR(100) NOT NULL COMMENT '密码',
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_at TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT  CURRENT_TIMESTAMP COMMENT '更新时间'
);


CREATE TABLE IF NOT EXISTS `category` (
    cid INT PRIMARY KEY AUTO_INCREMENT COMMENT '分类id',
    name VARCHAR(100) NOT NULL UNIQUE COMMENT '分类名字',
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_at TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT  CURRENT_TIMESTAMP COMMENT '更新时间'
);
INSERT INTO `category` (name) VALUES ('GO'), ('TS'), ('JAVA');

CREATE TABLE IF NOT EXISTS `post` (
    pid INT PRIMARY KEY AUTO_INCREMENT COMMENT '文章ID',
    title VARCHAR(100) NOT NULL UNIQUE COMMENT '文章标题',
    slug VARCHAR(1000) COMMENT '自定义页面path',
    content TEXT COMMENT '文章的html',
    markdown TEXT COMMENT '文章的Markdown',
    category_id INT COMMENT '分类id',
    user_id INT COMMENT '用户id',
    view_count INT DEFAULT 0 COMMENT '查看次数',
    type ENUM('0', '1') DEFAULT NULL COMMENT '文章类型 0 普通，1 自定义文章',
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_at TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT  CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY(category_id) REFERENCES category(cid) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(user_id) REFERENCES user(uid) ON DELETE CASCADE ON UPDATE CASCADE
)